name 'volgactf-final-main'
maintainer 'VolgaCTF'
maintainer_email 'aspyatkin@gmail.com'
license 'MIT'
description 'Install and configure VolgaCTF Final servers'
version '1.4.2'

depends 'ruby_rbenv', '~> 2.1.2'
depends 'redisio', '~> 3.0.0'
depends 'postgresql', '~> 7.1.4'
depends 'ntp', '~> 3.6.2'
depends 'firewall', '~> 2.7.0'
depends 'instance', '~> 2.0.1'
depends 'secret', '~> 1.0.0'
depends 'graphicsmagick', '~> 0.1.0'
depends 'git', '~> 9.0.1'
depends 'agit', '~> 0.1.2'
depends 'nodejs', '~> 6.0.0'
depends 'ngx', '~> 2.1.1'
depends 'ngx-modules', '~> 1.1.1'
depends 'line', '~> 2.4.1'
depends 'logrotate', '~> 2.2.0'
depends 'ssh_known_hosts', '~> 6.2.0'

depends 'volgactf-final', '~> 1.4.2'
depends 'docker', '~> 4.9.2'
depends 'netdata', '~> 0.4.1'
depends 'vpn', '~> 0.2.3'
